# Generated by Django 3.2.6 on 2021-08-19 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pays', '0006_pagar_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscricoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome do(a) aluno(a)')),
                ('sexo', models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], max_length=20, verbose_name='sexo')),
                ('idade', models.DecimalField(decimal_places=0, max_digits=2, verbose_name='idade')),
                ('nascimento_dia', models.DecimalField(decimal_places=0, max_digits=2, verbose_name='dia de nascimento')),
                ('nascimento_mes', models.CharField(choices=[('Janeiro', 'Janeiro'), ('Fevereiro', 'Fevereiro'), ('Março', 'Março'), ('Abril', 'Abril'), ('Maio', 'Maio'), ('Junho', 'Junho'), ('Julho', 'Julho'), ('Agosto', 'Agosto'), ('Setembro', 'Setembro'), ('Outubro', 'Outubro'), ('Novembro', 'Novembro'), ('Desembro', 'Desembro')], max_length=20, verbose_name='mês')),
                ('nascimento_ano', models.DecimalField(decimal_places=0, max_digits=4, verbose_name='Ano de nascimento')),
                ('cell1', models.DecimalField(decimal_places=0, max_digits=9, verbose_name='Tel.nº')),
                ('cell2', models.DecimalField(decimal_places=0, max_digits=9, verbose_name='outro Tel.n')),
                ('bi', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='Portador do B.I. Nº')),
                ('emitido', models.CharField(max_length=25, verbose_name='Emitido pelo Arquivo de')),
                ('distrito', models.CharField(max_length=20, verbose_name='Distrito')),
                ('bairro', models.CharField(max_length=20, verbose_name='Residente no bairro')),
                ('celula', models.CharField(max_length=15, verbose_name='Célula')),
                ('quarteirao', models.DecimalField(decimal_places=0, max_digits=6, verbose_name='Quarteirão')),
                ('casa', models.DecimalField(decimal_places=0, max_digits=5, verbose_name='Número de casa')),
                ('doenca', models.CharField(choices=[('SIM', 'SIM'), ('NÃO', 'NÃO')], max_length=3, verbose_name='Sofre de alguma doença?')),
                ('qual_doenca', models.CharField(max_length=15, verbose_name='Em caso afirmativo indintifique a doença')),
            ],
        ),
    ]
