# Generated by Django 3.2.6 on 2021-08-19 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pays', '0007_inscricoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscricoes',
            name='anterior',
            field=models.CharField(choices=[('7ª', '7ª'), ('8ª', '8ª'), ('9ª', '9ª'), ('10ª', '10ª'), ('11ª', '11ª'), ('12ª', '12ª')], max_length=9, null=True, verbose_name='No ano letivo anterir frequentou a'),
        ),
        migrations.AddField(
            model_name='inscricoes',
            name='aproveitamento',
            field=models.CharField(max_length=2, null=True, verbose_name='Aproveitamento do ano anterior'),
        ),
        migrations.AddField(
            model_name='inscricoes',
            name='cell_mae',
            field=models.DecimalField(decimal_places=0, max_digits=9, null=True, verbose_name='Telefone do Mãe'),
        ),
        migrations.AddField(
            model_name='inscricoes',
            name='cell_pai',
            field=models.DecimalField(decimal_places=0, max_digits=9, null=True, verbose_name='Telefone do pai'),
        ),
        migrations.AddField(
            model_name='inscricoes',
            name='classe',
            field=models.CharField(choices=[('8ª', '8ª'), ('9ª', '9ª'), ('10ª', '10ª'), ('11ª', '11ª'), ('12ª', '12ª')], max_length=9, null=True, verbose_name='PRETENDE MATRICULAR-SE NA'),
        ),
        migrations.AddField(
            model_name='inscricoes',
            name='curso',
            field=models.CharField(choices=[('diurno', 'diurno'), ('noturno', 'noturno')], max_length=10, null=True, verbose_name='No curso'),
        ),
        migrations.AddField(
            model_name='inscricoes',
            name='grupo',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B')], max_length=1, null=True, verbose_name='Grupo'),
        ),
        migrations.AddField(
            model_name='inscricoes',
            name='local_trabalho_mae',
            field=models.CharField(max_length=50, null=True, verbose_name='Local de trabalho do Mãe'),
        ),
        migrations.AddField(
            model_name='inscricoes',
            name='local_trabalho_pai',
            field=models.CharField(max_length=50, null=True, verbose_name='Local de trabalho do pai'),
        ),
        migrations.AddField(
            model_name='inscricoes',
            name='nome_mae',
            field=models.CharField(max_length=50, null=True, verbose_name='Nome do Mãe'),
        ),
        migrations.AddField(
            model_name='inscricoes',
            name='nome_pai',
            field=models.CharField(max_length=50, null=True, verbose_name='Nome do Pai'),
        ),
        migrations.AddField(
            model_name='inscricoes',
            name='profissao_mae',
            field=models.CharField(max_length=50, null=True, verbose_name='Profissão do Mãe'),
        ),
        migrations.AddField(
            model_name='inscricoes',
            name='profissao_pai',
            field=models.CharField(max_length=50, null=True, verbose_name='Profissão do pai'),
        ),
        migrations.AddField(
            model_name='inscricoes',
            name='seccao',
            field=models.CharField(choices=[('Todas Disc.', 'Tpdas Disc'), ('Secção de Letras', 'Secção de Letras'), ('Secção de Ciências', 'Secção de Ciências')], max_length=18, null=True, verbose_name='A preencher somente pelos alunos 10ª classe'),
        ),
        migrations.AddField(
            model_name='inscricoes',
            name='turma',
            field=models.CharField(max_length=3, null=True, verbose_name='Turma'),
        ),
    ]
