# Generated by Django 3.1.7 on 2021-04-01 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pays', '0007_delete_pagar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(choices=[('Diol Claudio', 'Diol Claudio'), ('joao fereira', 'joao fereira'), ('Loidmar tiwa', 'Loidmar Tibiwa'), ('Racia Muturumeliwa', 'Racia Muturumeliwa'), ('Elisa Ernesto', 'Elisa Ernesto')], max_length=50, verbose_name='Nome do aluno')),
                ('classe', models.CharField(max_length=20, verbose_name='Classe e Turma')),
                ('valor', models.DecimalField(decimal_places=5, max_digits=10)),
                ('mes', models.CharField(choices=[('Janeiro', 'Janeiro'), ('Fevereiro', 'Fevereiro'), ('Março', 'Março'), ('Abril', 'Abril'), ('Maio', 'Maio'), ('Junho', 'Junho'), ('Julho', 'Julho'), ('Agosto', 'Agosto'), ('Setembro', 'Setembro'), ('Outubro', 'Outubro'), ('Novembro', 'Novembro'), ('Desembro', 'Desembro')], max_length=20, verbose_name='mês')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
