# Generated by Django 3.1.7 on 2021-04-01 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pays', '0008_pagar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagar',
            name='classe',
            field=models.CharField(choices=[('8 classe, turma A', '8 classe, turma A')], max_length=50, verbose_name='Classe e Turma'),
        ),
    ]
