# Generated by Django 3.1.7 on 2021-04-01 13:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pays', '0009_auto_20210401_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagar',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pagar',
            name='valor',
            field=models.DecimalField(choices=[(2200, 2200)], decimal_places=5, max_digits=10),
        ),
    ]
