# Generated by Django 3.1.7 on 2021-04-07 09:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pays', '0010_auto_20210401_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='opiniao',
            field=models.TextField(verbose_name='opinão'),
        ),
        migrations.CreateModel(
            name='Informar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema', models.CharField(max_length=50, null=True, verbose_name='Tema da informacão')),
                ('info', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
