# Generated by Django 3.1.7 on 2021-04-07 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pays', '0011_auto_20210407_1135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informar',
            name='user',
        ),
    ]
